import type { Metadata } from 'next';
import '@/globals.css';
import { IRootLayout } from '@/generalTypes';
import { Header } from '@/modules';
import { Providers } from '@/Redux';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
